In [2]:
import numpy as np

In [4]:
np.arange(start=1, stop=11, step=1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# 파라미터명을 생략하고 순서대로 적어줘도 됨 (step은 기본값 1)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr = np.array([4,1,5,7,6,3,9,2,8])

In [8]:
# 오름차순
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 내림차순
np.sort(arr)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
# 만약 arr을 sort된 상태로 변경하고 싶다면
arr.sort()

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr_2d = np.array([[15,5,20,10],[9,3,6,12],[8,4,6,2]])

In [13]:
arr_2d

array([[15,  5, 20, 10],
       [ 9,  3,  6, 12],
       [ 8,  4,  6,  2]])

In [14]:
#같은 행 내에서 오름차순 정렬 (열정렬)
np.sort(arr_2d, axis=1)

array([[ 5, 10, 15, 20],
       [ 3,  6,  9, 12],
       [ 2,  4,  6,  8]])

In [15]:
#같은 열 내에서 오름차순 정렬 (행정렬)
np.sort(arr_2d, axis=0)

array([[ 8,  3,  6,  2],
       [ 9,  4,  6, 10],
       [15,  5, 20, 12]])

In [16]:
arr_2d = np.array([[15,5,20,10],[9,3,6,12],[8,4,6,2]])

In [17]:
arr_2d

array([[15,  5, 20, 10],
       [ 9,  3,  6, 12],
       [ 8,  4,  6,  2]])

In [18]:
#같은 행 내에서 오름차순 정렬 (열정렬)
np.argsort(arr_2d, axis=1)

array([[1, 3, 0, 2],
       [1, 2, 0, 3],
       [3, 1, 2, 0]], dtype=int64)

In [19]:
#같은 열 내에서 오름차순 정렬 (행정렬)
np.argsort(arr_2d, axis=0)

array([[2, 1, 1, 2],
       [1, 2, 2, 0],
       [0, 0, 0, 1]], dtype=int64)