In [20]:
arr_list = [[1,2,3],[4,5,6],[7,8,9]]
print(arr_list[0][2]) # 리스트의 0번 인덱스 안의 2번 인덱스
print(arr_list[2][0]) # 리스트의 2번 인덱스 안의 0번 인덱스

3
7


In [37]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

# 1행, 3열  --> 3
arr_2d[0,2]

# 3행, 1열  --> 7
arr_2d[2,0]

# 2행 모두  --> array([4,5,6])
arr_2d[1, :]

# 1열 모두 --> array([1,4,7])
arr_2d[:, 0]

# 3행의 1,2열 --> array([4,5])
print(arr_2d[2,0:2])

# 1,2행의 1,2열 --> array([1,2],[4,5])
print(arr_2d[0:2,0:2])

[7 8]
[[1 2]
 [4 5]]


In [40]:
arr = np.array([10,20,30,40,50])

# 보통 인덱싱
arr[1]

# 팬시 인덱싱
arr[[0,2,4]]

array([10, 30, 50])

In [46]:
arr_2d = numpy.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

# Boolean indexing

arr_2d > 2

# Boolean indexing 사용법

arr_2d[arr_2d > 5]

array([6, 7, 8, 9])