In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\usn14\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])


np.array([1,2,3,4], dtype=int)

array([1, 2, 3, 4])

In [12]:
my_list = [1,2,3,4]
my_list2 = [[1,2,3],[4,5,6]]   # 2행 3열

arr1 = np.array(my_list)
arr2 = np.array(my_list2)

arr1.shape

arr2.shape

(2, 3)

In [17]:
my_list = [1,2,3,4]

type(my_list)

list

In [18]:
my_ndarray = np.array([1,2,3,4])

type(my_ndarray)

numpy.ndarray

In [20]:
# ndarray는 한가지로 통일된 자료형으로 저장
my_ndarray = np.array([1,0.5,'python'])
my_ndarray

array(['1', '0.5', 'python'], dtype='<U32')

In [21]:
np.array([1,0.5,3])

array([1. , 0.5, 3. ])

In [22]:
np.array([1,0.9,3], dtype=int)

array([1, 0, 3])

In [23]:
np.array([1,0.5,'python',3], dtype=int)

ValueError: invalid literal for int() with base 10: 'python'

In [24]:
np.array([1,'2',3], dtype=int)

array([1, 2, 3])